name: myapp
description: "A new Flutter project with Firebase integration."
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: "^3.7.0-209.1.beta"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1 
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  dio: ^5.8.0+1
  flutter_map: ^8.1.0
  latlong2: ^0.9.1
  logger: ^2.5.0
  lottie: ^3.3.1
  image_picker: ^1.1.2
  provider: ^6.1.2
  tflite: ^1.1.2
  flutter_local_notifications: ^18.0.1
  firebase_messaging: ^15.2.4
  flutter_riverpod: ^2.6.1
  local_auth: ^2.3.0
  tflite_flutter: ^0.11.0
  ml_linalg: ^13.12.6
  path_provider: ^2.1.5
  archive: ^4.0.4
  http: ^1.3.0
  chewie: ^1.10.0
  video_player: ^2.9.3
  flutter_localizations:
    sdk: flutter
  mockito: ^5.4.5
  image: ^4.5.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true